# Render Deployment Configuration
# This file is used by Render for deployment

# Build configuration
build:
  type: maven
  buildCommand: mvn clean package -DskipTests
  startCommand: java -jar target/food-ordering-0.0.1-SNAPSHOT.jar

# Environment variables (set these in Render dashboard)
# SPRING_DATASOURCE_URL=jdbc:mysql://your-mysql-host:3306/mottamaadi_cafe
# SPRING_DATASOURCE_USERNAME=your_mysql_username
# SPRING_DATASOURCE_PASSWORD=your_mysql_password
# TWILIO_ACCOUNT_SID=your_twilio_sid
# TWILIO_AUTH_TOKEN=your_twilio_token
# TWILIO_PHONE_NUMBER=your_twilio_number
# ADMIN_PHONE_NUMBER=your_admin_number
# RAZORPAY_KEY_ID=your_razorpay_key_id
# RAZORPAY_KEY_SECRET=your_razorpay_key_secret
# STRIPE_PUBLISHABLE_KEY=your_stripe_publishable_key
# STRIPE_SECRET_KEY=your_stripe_secret_key
# FIREBASE_PROJECT_ID=your_firebase_project_id
# FIREBASE_SERVICE_ACCOUNT_KEY=path/to/service-account-key.json

# Service configuration
service:
  type: web
  port: 9090
  healthCheckPath: /
  autoDeploy: true
  branch: main
